### ISSUE TITLE
Fix links

### ISSUE THREAD

**Issue by patricia-ternes** [ARCTraining/hackpad-templator#35]
The links here are not working

https://github.com/ARCTraining/hackpad-templator/blob/e0fcb30ac1ecb6435213f89a5ade131ab67a946c/templates/hpc0.md.j2#L21-L22

change the slides to: https://docs.google.com/presentation/d/1-iMN4PQ8gt2HEw5kERHDSY-OzcFK-Rrz/edit?rtpof=true
change the solution to: (?)

**Comment by agdturner** [comment]
I think this has been fixed.
